# Generated by Django 2.1.1 on 2018-12-23 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_app', '0002_auto_20181110_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='名称')),
                ('response_url', models.TextField(default='', verbose_name='URL')),
                ('response_method', models.TextField(default='', max_length=100, verbose_name='方法')),
                ('response_type', models.TextField(default='', max_length=100, verbose_name='参数类型')),
                ('response_header', models.TextField(default='', verbose_name='header')),
                ('response_parameter', models.TextField(default='', verbose_name='参数')),
                ('response_assert', models.TextField(default='', verbose_name='断言')),
                ('status', models.BooleanField(choices=[(True, '开启'), (False, '关闭')], verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.Module')),
            ],
            options={
                'verbose_name': '用例管理列表',
                'verbose_name_plural': '用例管理列表',
            },
        ),
        migrations.CreateModel(
            name='TestTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='任务名称')),
                ('describe', models.TextField(default='', max_length=100, verbose_name='任务描述')),
                ('status', models.CharField(choices=[('y0', '未执行'), ('y1', '执行中'), ('y2', '排队中'), ('y3', '执行完成'), ('y4', '故障中')], default='y0', max_length=10, verbose_name='任务状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('case_id', models.ManyToManyField(to='interface_app.TestCase')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='任务创建者')),
            ],
            options={
                'verbose_name': '任务管理表',
                'verbose_name_plural': '任务管理表',
            },
        ),
        migrations.CreateModel(
            name='TestTaskRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField(verbose_name='任务执行结果')),
                ('work_start_time', models.DateTimeField(verbose_name='任务开始时间')),
                ('work_end_time', models.DateTimeField(verbose_name='任务结束时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('name', models.CharField(default='', max_length=100, verbose_name='名称')),
                ('error', models.IntegerField(verbose_name='错误用例')),
                ('failure', models.IntegerField(verbose_name='失败用例')),
                ('skipped', models.IntegerField(verbose_name='跳过用例')),
                ('tests', models.IntegerField(verbose_name='总用例数')),
                ('run_time', models.FloatField(verbose_name='运行时长')),
                ('result_describle', models.TextField(default='', verbose_name='详细')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='任务执行者')),
                ('testtask_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface_app.TestTask', verbose_name='测试任务id')),
            ],
            options={
                'verbose_name': '任务执行记录表',
                'verbose_name_plural': '任务执行记录表',
            },
        ),
    ]
