# Generated by Django 2.1.1 on 2018-11-10 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_app', '0002_auto_20181110_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='名称')),
                ('response_url', models.TextField(default='', verbose_name='URL')),
                ('response_method', models.TextField(default='', max_length=100, verbose_name='方法')),
                ('response_type', models.TextField(default='', max_length=100, verbose_name='参数类型')),
                ('response_header', models.TextField(default='', verbose_name='header')),
                ('response_parameter', models.TextField(default='', verbose_name='参数')),
                ('response_assert', models.TextField(default='', verbose_name='断言')),
                ('status', models.BooleanField(choices=[(True, '开启'), (False, '关闭')], verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.Module')),
            ],
            options={
                'verbose_name': '用例管理列表',
                'verbose_name_plural': '用例管理列表',
            },
        ),
    ]
