# Generated by Django 2.1.1 on 2018-11-10 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_auto_20181110_1458'),
        ('interface_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Case',
            new_name='TestCase',
        ),
    ]
