# Generated by Django 2.1.1 on 2018-12-04 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0003_testtask_testtaskrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtask',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.UserInfo', verbose_name='任务创建者'),
        ),
    ]
