# Generated by Django 2.1.1 on 2018-12-04 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0004_auto_20181204_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtask',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='任务创建者'),
        ),
        migrations.AlterField(
            model_name='testtaskrecord',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='任务执行者'),
        ),
    ]
