# Generated by Django 2.1.1 on 2018-11-10 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.Project', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.BooleanField(choices=[(True, '开启'), (False, '关闭')], verbose_name='状态'),
        ),
    ]
